title: MY Blog
logo_url: ''
social:
  - github
  - twitter
defaults:
  - values:
      layout: "default"
      icon: "book"
rss: rss
theme: jekyll-aquarius
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2s
comments:
  gitalk: true
autopages:
  enabled: true
# 分页
pagination:
  enabled: true
  # collection: 'posts'
  extension: html
  permalink: '/:num/'
  title: ':title | :num of :max'
  sort_field: 'date'
  sort_reverse: true
  per_page: 6
  limit: 0
  trail:
    before: 2 # The number of links before the current page
    after: 2
