title: MY Blog
logo_url: ''

social:
  - github
  - twitter
defaults:
  - values:
      layout: "default"
      icon: "book"
rss: rss
theme: jekyll-aquarius
plugins:
 - jekyll-feed
 - jekyll-seo-tag
comments:
  gitalk: true
